---
language: java
jdk: openjdk11
dist: xenial

git:
  depth: false
  quiet: true

services:
  - docker

cache:
  directories:
    - ${HOME}/.m2/repository

branches:
  only:
    - master
    - release
    - /^ATS-.*$/
    - /^REPO-.*$/
    - ATS-545_custom_release

stages:
  - build
  - release

jobs:
  include:
    - name: "Build + Tests"
      stage: build
      before_install: bash _ci/init.sh
      script: bash _ci/build.sh

    - name: "WhiteSource"
      stage: build
      before_install: bash _ci/init.sh
      script: bash _ci/whitesource.sh

    - name: "Release"
      stage: release
      if: branch = ATS-545_custom_release
      before_install: bash _ci/init.sh
      script: bash _ci/release.sh
